version: 2
models:
  - name: stg_nations
    description: List of all countries
    columns:
      - name: nation_id
        tests:
          - unique
          - not_null
      - name: region_id
        tests:
          - not_null
  - name: stg_regions
    columns:
      - name: region_id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_nations')
              field: region_id
      - name: name
        tests:   
          - accepted_values:
              values: ['ASIA','AFRICA','AMERICA']
              config:
                  - store_failures: true
